version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:14.10.1
        steps:
            - checkout
            - run: yarn install
            - run: CI=true yarn build
    test:
        docker:
            - image: cimg/node:14.10.1
        steps:
            - checkout
            - run: yarn install
            - run: yarn test
